### ISSUE TITLE
Trouble using the pre-built MacOS binary

### ISSUE THREAD

**Issue by tobyrmanders** [zoni/obsidian-export#107]
Sorry for the noob question -- but when I try to run the MacOS binary as described in the README, I have issues. 

Attempt 1:
```
❯ ~/Downloads/obsidian-export --version
zsh: no such file or directory: /Users/toby.manders/Downloads/obsidian-export
```

Attempt 2:
```
❯ ~/Downloads/obsidian-export_MacOS-x86_64.bin --version
zsh: permission denied: /Users/toby.manders/Downloads/obsidian-export_MacOS-x86_64.bin
```

Attempt 3:
```
❯ sudo ~/Downloads/obsidian-export_MacOS-x86_64.bin --version
Password:
sudo: /Users/toby.manders/Downloads/obsidian-export_MacOS-x86_64.bin: command not found
```

Attempt 4:
```
❯ ~/Downloads/obsidian-export_MacOS-x86_64 --version
zsh: no such file or directory: /Users/toby.manders/Downloads/obsidian-export_MacOS-x86_64
```

Is there something I need to do with the binary before calling it from the command line?

**Comment by dmentipl** [comment]
Hi @tobyrmanders, it's likely that the binary does not have executable permissions. If you run `ls` in the directory in which you downloaded the binary,

```bash
❯ cd ~/Downloads
❯ ls -l
-rw-r--r--  1 username  staff  2793824 22 Jun 09:14 obsidian-export_MacOS-x86_64.bin
```

you can see that the permissions, `-rw-r--r--`, indicate that the binary is not executable. (See, for example, [this webpage](https://docs.nersc.gov/filesystems/unix-file-permissions/) for an explanation of Unix file permissions.)

To make it executable use `chmod` as follows,

```bash
❯ chmod +x obsidian-export_MacOS-x86_64.bin
```

and check that the file permissions have changed,

```bash
❯ ls -l
-rwxr-xr-x  1 username  staff  2793824 22 Jun 09:15 obsidian-export_MacOS-x86_64.bin
```

and that you can run the program,

```bash
❯ ./obsidian-export_MacOS-x86_64.bin --version
obsidian-export 22.1.0
```

Hopefully that helps.

**Comment by tobyrmanders** [comment]
Worked great. Thank you!
