### ISSUE TITLE
Visually identical UTF-8 composites are not threatened as equal (E.g. filenames with umlauts created by Windows under OSX).

### ISSUE THREAD

**Issue by oderwat** [zoni/obsidian-export#126]
I have embedded notes that link to files with German umlauts. The exporter reports that the file is not to be found. It is shown in Obsidian, and it works after renaming the file (+embedded link name).

**Comment by zoni** [comment]
Hi @oderwat, I'm unable to reproduce this issue. A note with the title `obsidian export issue 126 ümlàuts` exports just fine for me.

However, please note that filenames **must** be encoded as UTF-8 for this to work. From https://github.com/zoni/obsidian-export#character-encodings:

> At present, UTF-8 character encoding is assumed for all note text as well as filenames. All text and file handling performs [lossy conversion to Unicode strings](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8_lossy).
>
> Use of non-UTF8 encodings may lead to issues like incorrect text replacement and failure to find linked notes. While this may change in the future, there are no plans to change this behavior in the short term.

While supporting other encoding schemes is possible, doing so introduces additional complexity and more error-cases to check against. Enforcing a consistent UTF-8 worldview significantly simplifies some of the logic and is not something I am interesting in changing at this time.

(If you are certain your notes are already UTF-8 and it's still not working, then that would be a valid bug I'd be happy to look at)

**Comment by oderwat** [comment]
I am on OSX and this encodes filenames as UTF-8 for sure. Did you use the `obsidian export issue 126 ümlàuts.md` as an embedded link and exported the file where it is embedded?

**Comment by oderwat** [comment]
I think I found the problem. The filename umlauts for this vault are a mixture between files that got created on windows and files that got created on OSX. I know from some other programs I wrote that Windows loves to use another UTF-8 variant to show the same character esp. in filenames.

`ä` vs `ä` 

The first one is 2 bytes: 195 164
The second one is 3 bytes: 97 204 136

You may copy & paste them from here as an example.

So technically, both are UTF-8 and both are valid in Text and in filenames. It seems that Obsidian does support that, but your code does not. I think you could use `https://docs.rs/unicode-normalization/latest/unicode_normalization/` to make your program handle this problem!

**Comment by zoni** [comment]
Just to make sure we're on the same page here:

1.You have a note with `ä` (2 bytes: 195 164) in the filename.
2. You write another note where you input that same title "manually" without using Obsidian's autocomplete, which ends up expanding it to `![[something something ä]]` (3 bytes: 97 204 136).
3. Obsidian-export cannot find the note, because *technically*, it links to a different file. However, visually it looks the same and as a user, you'd expect this to "just work" and find/export that note.
4. Furthermore, Obsidian itself actually handles this differently/properly (it resolves the link as you would expect)

Is that right?

**Comment by oderwat** [comment]
I have notes with both variants in the filenames as the repository is cloud shared with a Windows user and we both create and change notes. When I see it right, Obsidian has mostly the 2 bytes version for all links. When I drag a 3 byte variant of the file inside the note on my Mac the text inside the editor is converted to the 2 byte version, when I copy and paste the filename from Finder into the text it is the 3 byte version. Both of them link in Obsidian to the 3 byte variant file. When I rename it in Finder to the 2 byte variant (which I can do by cut the name and paste it again) Obsidian still finds that file for both. Interestingly, the new "obsidian42 strange new worlds" lists a different usage count for them, but Obsidian shows the same outgoing links for both of them. So, this plugin also seems to struggle with the treating them equally.

**Comment by zoni** [comment]
I should have a fix ready for this later today or somewhere this weekend! :smile:

**Comment by oderwat** [comment]
Great!
