### ISSUE TITLE
Windows Documentation

### ISSUE THREAD

**Issue by eleanorkonik** [zoni/obsidian-export#13]
1.  I downloaded the windows release from github. I put the file into a the folder I created with MKDocs, which I copied part of my obsidian vault into (a folder called “Gardening”). I then made a folder called “Export” in the same directory.
2.  Tried to run obsidian-export. Got an error about it not being recognized.
3.  Opened the file in notepad++ and saw it was appended as “mz” so I changed to a .exe file
4.  Tried to run it again using `obsidian-export` but powershell threw a “suggestion” because    

> The command obsidian-export was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\\obsidian-export". See "get-help about\_Command\_Precedence" for more details.

5.  so I tried: `PS D:\notes> .\obsidian-export my-obsidian-vault /tmp/export` which returned `Error: No such file or directory: my-obsidian-vault`
6.  so I tried: `.\obsidian-export Gardening /Export` which didn’t work (no such file or directory).
7.  However, `.\obsidian-export Gardening Export` worked fine.

**Comment by zoni** [comment]
Hey Eleanor,

Bit late in getting back to this, but with the help of your write-up I added some additional pointers to the "Basic usage" instructions in the README. I think this strikes a good balance of remaining concise and to the point while still giving sufficient pointers for people who are largely unfamiliar with command-line interfaces.

Thanks you for taking the time to write this up!
