### ISSUE TITLE
preserve mtime of source file

### ISSUE THREAD

**Issue by reagle** [zoni/obsidian-export#154]
When using pandoc, I check if the source markdown is newer than the resulting HTML; if so, I know I need to run pandoc on the markdown but can otherwise skip it. If you preserved the source `mtime`, this would be very easy -- otherwise, I'll need to copy `mtime` from the source myself.

**Comment by zoni** [comment]
This has been addressed with https://github.com/zoni/obsidian-export/pull/204, which will be available with the next release.
