### ISSUE TITLE
Export only labeled files

### ISSUE THREAD

**Issue by uPagge** [zoni/obsidian-export#161]
I would like to be able to export only explicitly selected files.

For example, the choice could be made using the export parameter: true
 
```file.md
---
alias: test
export: true
---
\# h1 
Content
```

**Comment by epsilonhalbe** [comment]
duplicate of issue #66 
fixed by PR #163

**Comment by epsilonhalbe** [comment]
@zoni @uPagge i think this can be closed

**Comment by zoni** [comment]
Indeed!
