### ISSUE TITLE
Feature Request:  continue even if error

### ISSUE THREAD

**Issue by markfaine** [zoni/obsidian-export#189]
It seems like if even the most insignificant issue comes up it exits completely.  Can it, either by default or as a flag, keep going and just warn on errors.  Missing links and such don't matter to the overall run, I just want it to process the entire directory and warn me of any issues.

**Comment by zoni** [comment]
What you describe is very different from the behavior I experience in practice. In fact, the example you have given is explicitly already treated as non-fatal both [for embeds](https://github.com/zoni/obsidian-export/blob/eb4c0092076669e785e929ee6e3142857a073516/src/lib.rs#L576-L584) and [regular links](https://github.com/zoni/obsidian-export/blob/eb4c0092076669e785e929ee6e3142857a073516/src/lib.rs#L661-L673).

Could you please provide specific examples of where it exits completely in a way you find unexpected, ideally with (example or sanitized) note contents and output of obsidian-export?

**Comment by markfaine** [comment]
You are correct, sorry to have bothered you.
