### ISSUE TITLE
Embedded link blocks don't work properly

### ISSUE THREAD

**Issue by jericjan** [zoni/obsidian-export#198]
When I do embedded link blocks, it seems to just copy over the entire contents of the embed note, instead of just the block.

### text1.md
```markdown

text i want to embed ^1b527a

other text

```

### text2.md
```markdown
[[text1^1b527a]]
```

Result:
### text2.md
```markdown
text i want to embed ^1b527a

other text
```

**Comment by swanandx** [comment]
I am also facing same issue, hope this gets resolved ASAP. For now, I have to remove all those block links :sob:

**Comment by zoni** [comment]
This is currently not implemented unfortunately. Please feel free to [upvote and/or comment on the feature request for this](https://github.com/zoni/obsidian-export/discussions/60).

While this is something I would ultimately like to support, I would not expect it to be implemented any time soon. It's rather complex to incorporate, and to date, I've not had the motivation to take on all that work.
