### ISSUE TITLE
Does it support tags?

### ISSUE THREAD

**Issue by jca41** [zoni/obsidian-export#31]
For ex. `#something` will it convert this to a specific html element so we can style it accordingly?

**Comment by zoni** [comment]
No, it treats this as regular text and will leave it untouched. My goal with obsidian-export is to try to stay as close to the source markdown as possible and leave such processing to other tools.

[The underlying library allows postprocesing](https://docs.rs/obsidian-export/0.7.0/obsidian_export/type.Postprocessor.html) which would let you do this, but this kind of functionality isn't currently exposed by the CLI command yet.
