### ISSUE TITLE
Inconsistent behavior when exporting ![[image.svg]] vs ![[image.png]]

### ISSUE THREAD

**Issue by nsainaney** [zoni/obsidian-export#42]
Hi there,
Great library! It's exactly what we needed.

I have a source file with:

```
![[CLI.svg]]
![[CLI.png]]
```

and the exported file results in:

```
[CLI.svg](_fragments/_gen_media/CLI.svg)
![CLI.png](_fragments/_gen_media/CLI.png)
```

The svg is missing the exclamation mark. I'd love to be able to submit a PR however, I've never done any rust coding. Would appreciate a fix or direction on where this fix would need to be.

Thanks!

```
> obsidian-export --version
obsidian-export 21.9.0
```

**Comment by zoni** [comment]
Hey @nsainaney, the list of extensions that are treated as embeddable images is defined here: https://github.com/zoni/obsidian-export/blob/6d247104c45f8128e0efef3288bf6623c34d3cba/src/lib.rs#L630

Just adding an extra `Some("svg")` match clause there would be sufficient. I think that would be totally reasonable, so if you make a PR I'll happily merge and make a new version :smile:

**Comment by nsainaney** [comment]
Hi @zoni , 
Any chance this can be published to crates.io? We have our CI/CD pipelines using `obsidian-export` and it'd be nice to get this working.

Thanks!

**Comment by zoni** [comment]
I'll happily accept [coffee bribes](https://ko-fi.com/nickgroenen) to speed up reviews and new releases. :wink:

**Comment by zoni** [comment]
New release is out!
