### ISSUE TITLE
Release file is without a filetype.

### ISSUE THREAD

**Issue by emrergin** [zoni/obsidian-export#49]
As a newbie to everything coding related, I don't understand what to do with the precompiled file.

**Comment by zoni** [comment]
It's an application binary that you need to run from within a terminal/shell environment. Are you a Windows user, or Mac/Linux?

**Comment by emrergin** [comment]
I see, I thought I would have an exe file.

I am a Windows user.

**Comment by zoni** [comment]
I've made sure release artifacts on Windows have a `.exe` extension going forward, which hopefully helps future users avoid this confusion.
