### ISSUE TITLE
Generated paths are not working out of the box under windows with HUGO

### ISSUE THREAD

**Issue by SR-G** [zoni/obsidian-export#7]
Hello,

I think i have a WINDOWS issue.
1. In OBSIDIAN, i have links like ![[Pasted Image.png]]
2. When `obsidian-export` is launched, i then have in generated .md in the output markdown paths like : 
`![Pasted image 20210201170521.png](..\..\resources\2021\images\Pasted%20image%2020210201170521.png)`
3. When i launch HUGO on these markdown file, i then have target URL like : 
`http://localhost:1313/daily/2021/02/....%5Cresources%5C2021%5Cimages%5CPasted%20image%2020210201170513.png`

Note : 
- the `....` pattern (i don't know why here the "\" has disappeared)
- the fact that "\" are replaced by "5C"

So, maybe, would it be possible to have "/" for the paths ?
Or any other idea ?

**Comment by zoni** [comment]
I will close this issue for the same reasons as closing #8.
